### ISSUE TITLE
关于训练过程的疑问

### ISSUE THREAD

**Issue by lds-0107** [DEVILENMO/Unsupervised-Defect-Detection-Project-Based-on-VAE-GAN-Architecture#4]
运行VAE_GAN_train.py时终端一直没有输出，后台也没显示GPU内存占用，请问是正常现象吗？后续会有训练结果输出么？

**Comment by DEVILENMO** [comment]
> 运行VAE_GAN_train.py时终端一直没有输出，后台也没显示GPU内存占用，请问是正常现象吗？后续会有训练结果输出么？

你好，后来问题解决了吗？忙着工作没看自己github，有问题的话可以再问我

**Comment by lds-0107** [comment]
> > 运行VAE_GAN_train.py时终端一直没有输出，后台也没显示GPU内存占用，请问是正常现象吗？后续会有训练结果输出么？
> 
> 你好，后来问题解决了吗？忙着工作没看自己github，有问题的话可以再问我

感谢回复😊我后来自己加了一些监测运行过程的调试代码，可以正常运行输出，已经没什么问题了

**Comment by DEVILENMO** [comment]
> > > 运行VAE_GAN_train.py时终端一直没有输出，后台也没显示GPU内存占用，请问是正常现象吗？后续会有训练结果输出么？
> > 
> > 
> > 你好，后来问题解决了吗？忙着工作没看自己github，有问题的话可以再问我
> 
> 感谢回复😊我后来自己加了一些监测运行过程的调试代码，可以正常运行输出，已经没什么问题了

好的好的，不客气
